
constexpr const char* gamma_convert_vs_glsl = "#version 310 es\n"
"\n"
"// Thanks Xyonico for these shaders!\n"
"// Apparently from https://stackoverflow.com/questions/31482816/opengl-is-there-an-easier-way-to-fill-window-with-a-texture-instead-using-vbo/31501833#31501833\n"
"\n"
"layout (location = 0) out vec2 texCoords;\n"
"\n"
"const vec2 pos[4] = vec2[4](\n"
"    vec2(-1.0, 1.0),\n"
"    vec2(-1.0,-1.0),\n"
"    vec2( 1.0, 1.0),\n"
"    vec2( 1.0,-1.0)\n"
");\n"
"\n"
"void main() {\n"
"    texCoords = 0.5 * pos[gl_VertexID] + vec2(0.5);\n"
"    // Flip image upside down. glReadPixels will flip it again, so we get the normal image.\n"
"    texCoords.y = 1.0 - texCoords.y;\n"
"\n"
"    gl_Position = vec4(pos[gl_VertexID], 0.0, 1.0);\n"
"}\n"
;
