
constexpr const char* gamma_rgb_convert_fs_glsl = "#version 310 es\n"
"\n"
"// Shader from xyonico, thank you very much!\n"
"\n"
"precision mediump float;\n"
"\n"
"uniform sampler2D cameraTexture;\n"
"\n"
"layout (location = 0) in vec2 texCoords;\n"
"\n"
"out vec4 out_rgba;\n"
"\n"
"void main() {\n"
"    const float gamma = 1.0 / 2.2;\n"
"    vec3 color = texture(cameraTexture, texCoords).rgb;\n"
"    color = pow(color, vec3(gamma));\n"
"\n"
"    out_rgba = vec4(color, 1.0f);\n"
"}\n"
;
